### ISSUE TITLE
Version mismatch between client and server

### ISSUE THREAD

**Issue by robes** [informatics-isi-edu/microscopy#1]
The _webcli_ client is using a feature `@SORT(...)` that is not supported by the __cirm-deploy-3__ tagged version of _ERMrest_ which we have instructed users to install. What version _does_ work with this Microscopy solution?

**Comment by svoinea** [comment]
cirm-deploy-3 UI is only under https://svn2.misd.isi.edu/repos/tagfiler/projects/cirm/tags/cirm-deploy-3, and there, the file is for example cirm.js and not app.js.

I have checked and that file has no "@sort", i.e. it is consistent with cirm-deploy-3 for ermrest and webauthn2.

Most likely, they have the latest webcli (https://svn2.misd.isi.edu/repos/tagfiler/projects/microscopy/trunk/webcli). There is no tag under https://svn2.misd.isi.edu/repos/tagfiler/projects/microscopy.

**Comment by robes** [comment]
We decided to test the Microscopy app against the latest source from ERMrest and it appears to be working. Recommendation is to use ERMrest 'master' branch. Documentation has been updated.
