### ISSUE TITLE
Use Zeiss DZI tool see if we can produce full resolution TIFF for DZI.

### ISSUE THREAD

**Issue by carlkesselman** [informatics-isi-edu/microscopy#12]

**Comment by karlcz** [comment]
This seems obsolete?

**Comment by carlkesselman** [comment]
Yes.  Can be closed.

Sent from my iPhone

On Nov 19, 2015, at 10:55 AM, karlcz <notifications@github.com<mailto:notifications@github.com>> wrote:


This seems obsolete?

-
