### ISSUE TITLE
Use Default Colors specified in XML file.

### ISSUE THREAD

**Issue by carlkesselman** [informatics-isi-edu/microscopy#16]
Pass through and use default colors in XML file from CXI.  The specification should be:
* NAME  — name of the channel, to be used in the channel selector. Used to pick * default color if COLOR not otherwise specified.
* COLORALPHA — Value of Alpha channel. To default to 1 if not specified (although we need to make it  .9 for now until we fix the opacity value issue)  If the value coming in is FF for now we should clamp until .9 until we have the fix.
* COLORRGB  — Default color to start the channel at.

**Comment by meihuisu** [comment]
done..
