### ISSUE TITLE
Fix Contrast Control to behave properly.

### ISSUE THREAD

**Issue by carlkesselman** [informatics-isi-edu/microscopy#20]
Contrast should change the slope and zero-intercept of the color ramp.  It should support a symmetric adjustment to either increase or decrease the slope with an identity transform as its center and default behavior:
- Contrast `0.5` would map input range [0, 1] to output [0.25, 0.75]
- Contrast `1` would map input range [0, 1] to output [0, 1]
- Contrast `2` would map input range [0.25, 0.75] to output [0, 1] clamping all inputs below 0.25 to 0 and inputs above 0.75 to 1.0

For clarity on the math (not that the UI should support this):
- As contrast goes to `1/infinity` it would map full input range to output 0.5, i.e. slope is 0.
- As contrast `infinity` it would clamp all inputs 0.5 or lower to 0 and all above 0.5 to 1, i.e. slope is infinity.

**Comment by meihuisu** [comment]
I put in a new constrast filter with range -100 to 100 based on,
//http://stackoverflow.com/questions/3115076/adjust-the-contrast-of-an-image-in-c-sharp-efficiently/3115178#3115178

**Comment by carlkesselman** [comment]
Karl: can you validate that this is behaving as you would expect?

**Comment by karlcz** [comment]
This got lost in backlog rather than review stage... @meihuisu is this still something that can/should be reviewed?  If so, could you point me at an image viewer URL where I can try it?

**Comment by meihuisu** [comment]
No need to review since this feature is not being exercised at this point. 

----- Original Message -----

**Comment by karlcz** [comment]
This issue is still parked in review. What codebase does it apply to?  I think the brightness/contrast is working reasonably in the recent openseadragon demos I've seen.

@meihuisu @carlkesselman @hongsudt

**Comment by karlcz** [comment]
Closing this due to lack of response...
