### ISSUE TITLE
Make the Print Label button work better

### ISSUE THREAD

**Issue by robes** [informatics-isi-edu/microscopy#29]
Can't think of a good title for this!

The Print Label button was a clever hack using markdown templates in Chaise. Its really just an html anchor link that opens a new window.

What we really need is for it to invoke the printer without opening a new window. The user feedback on it is that its a little bit of a nuisance (no suprise) to have to close that window after each time you click print. They would be satisfied if it were a popup that can be dismissed.

Probably what we really want is to be able to invoke some javascript function on click so that we can do more customized behavior. Need to discuss this with the UI team.

**Comment by robes** [comment]
@hongsudt @karlcz maybe we can discuss this sometime. I'd like to get your input on this.

**Comment by karlcz** [comment]
What about making a tiny "print label" app that can be embedded in an iframe?

**Comment by robes** [comment]
I like that idea. And from what I've seen we can put iframes even in attributes (columns) not just nested tables.

Currently, we show these Print Label "buttons" on the detail and compact views of Slides and Experiments.

**Comment by robes** [comment]
@svoinea this should be easy

**Comment by svoinea** [comment]
@robes A version is available on `cirm-staging` for review. The results of printing labels is just simulated.

**Comment by robes** [comment]
@svoinea Okay, the mechanism is right.

However, I quickly managed to generate an 'internal server error' by, clicking Print, OK, Print, OK,... until Print resulted in 'internal server error'.

And then when that is fixed, next up is the styling.

**Comment by svoinea** [comment]
@robes The log file was reporting an error I know I have fixed it. It's possible that I didn't restart the `httpd` service after I installed the new Python package, and therefore Apache was running also older Python processes. While I was able to recreate once the reported bug, now, after I have restarted the `httpd` service, it does not appear any more to me. 

Please retry the test.

**Comment by svoinea** [comment]
@robes I have added some styling for displaying the URL links as buttons and setting a `black` background to the `Print Label` iframe.

**Comment by robes** [comment]
Can you make the iframe smaller, background white. And the results page can be less verbose.

> Message (##) [OK]

It doesn't need to say "Result code: ..." and "Result message: ..." on separate lines as it does not.

**Comment by svoinea** [comment]
@robes I have reduced the `iframe` dimensions to `height=75 width=150`. Setting lower values ends up in generating scroll bars.

The normal result is displaying now only the message `Success` and the `OK` button.  (on `cirm-staging`, being just a simulation, the displayed message is `Success (Test)`).

In case of an error, the error message will be displayed instead.

**Comment by robes** [comment]
1. Center the response text "Success (Test)".
2. Add some padding (of space) between the message and the [OK] button.
3. Why does the message say "...(Test)"??
4. Is there some style you can apply to the iframe (the enclosing iframe generated by markdown) to get rid of the 3-dimensional impression effect?

**Comment by svoinea** [comment]
@robes 
1. Done.
2. Done.
3. As I explained above, ` (Test)` appears only on `cirm-staging` where we just simulate a `print label`. On `cirm-www` it is just `Success`.
4. At this time, I have no clue on how to do it. The Wiki is mentioning that the annotation is just adding `<figure class="embed-block">...<iframe ... ></iframe></figure>`.

**Comment by robes** [comment]
Regarding 4, can you check on the chaise chatroom to see if there is any way to adjust the styling of an iframe?

**Comment by karlcz** [comment]
The purpose of the class attribute shown in the previous message is so
that you can apply custom CSS to that element and class within your own
deployment.

**Comment by svoinea** [comment]
@robes 
I have added to the `iframe` annotation the following style for the border:

`border-style: solid; border-color: rgb(153, 153, 153);`
