### ISSUE TITLE
aggregated Probes and Genes are somewhat broken on Scans

### ISSUE THREAD

**Issue by robes** [informatics-isi-edu/microscopy#33]
We are using functions to aggregate the Probes (associated with Experiments) and Genes (associated with Specimens) in denormalized array columns of the Scans. This was done so that you could view all probes/genes related to a scan. However, the functionality is incomplete and kind of broken. For example, these array columns show up in the facet controls but you can't search on them. Also, they show up in "raw" arrays `['apeala','gfp']`.

To make this function complete we need:
- [ ] use markdown template to display the values rather than showing the raw array output
- [ ] facet on the real columns not the denormalized columns; i.e., `scan -> experiment -> experiment_probe -> probe.name`
- [ ] and do not show the facet of the denormalized array

**Comment by svoinea** [comment]
@robes From what I see so far, the single broken thing is the appearance of the `Probes` facet in the `Scan` table. It should be hidden.

However, the `Scan` table has the `Probe` facet where you can search based on a single value.

The `Experiment` and `Specimen` tables have not facets with array values.

**Comment by svoinea** [comment]
Defined the new `Probes` and `Genes` facets on all the three `CIRM` VMs (`cirm-dev`, `cirm-staging` and `cirm-www`).

For the `Scan` table:
```
Genes: Scan --> Specimen <-- specimen_gene --> Gene (term)
Probes: Scan --> Experiment <-- experiment_probe --> Probe (term)
```
For the `Specimen` table:
```
Genes: Specimen <-- specimen_gene --> Gene (term)
```
For the `Experiment` table:
```
Probes: Experiment <-- experiment_probe --> Probe (term)
```
I have committed in the `microscopy` repository, under the `config` directory, the files used to redefined the `tag:isrd.isi.edu,2016:visible-columns`:
```
 - scan_visible_columns.json
 - specimen_visible_columns.json
 - experiment_visible_columns.json
```

**Comment by robes** [comment]
looks good
