### ISSUE TITLE
scanTiler should tile for 'dzi' format for sea dragon viewer

### ISSUE THREAD

**Issue by robes** [informatics-isi-edu/microscopy#4]
Currently scanTiler checks whether the 'tiles' attribute is null (on the scan table) and if so run the tiling script on the original image to produce the tiles. We should instead start checking on the 'dzi' attribute. We only need to produce the dzi tiles now. We could drop zoomify tiling altogether or keep it as a conditional code path.

**Comment by meihuisu** [comment]
Serban said he will take care of this.

**Comment by karlcz** [comment]
@svoinea @hongsudt @robes  I think this issue is obsolete and some other solution is already in place. Closing this.
